apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::937745772157:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EV8OA0NH6XCQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
       - system:masters
      rolearn: arn:aws:iam::937745772157:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T21:38:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1472"
  uid: fe17263b-3224-4613-8b35-ab2a09ef2499
